[phases.setup]
nixPkgs = ['nodejs-18_x', 'yarn']

[phases.install]
cmds = ['yarn install --frozen-lockfile']

[phases.build]
cmds = ['yarn build']

[start]
cmd = 'yarn start'

# Alternative Railway start command with webhook setup
# cmd = 'yarn start:railway'
